(cl:in-package ground_commands-msg)
(cl:export '(X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          X_DOT-VAL
          X_DOT
          Y_DOT-VAL
          Y_DOT
          Z_DOT-VAL
          Z_DOT
          PSI-VAL
          PSI
          THETA-VAL
          THETA
          PHI-VAL
          PHI
          PSI_DOT-VAL
          PSI_DOT
          THETA_DOT-VAL
          THETA_DOT
          PHI_DOT-VAL
          PHI_DOT
          MAG_X-VAL
          MAG_X
          MAG_Y-VAL
          MAG_Y
          MAG_Z-VAL
          MAG_Z
))